// HotOnes - C++ main
// Generated by Meow
#include <Hotones.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <raylib.h>

#include <vector>
#include <cstdint>
#include <cmath>
#include <thread>
#include <chrono>
#include <SoundBus.hpp>



int main() {
    // Initialize the window
    InitWindow(800, 600, "HotOnes");

    // Main game loop
    while (!WindowShouldClose()) {
        // Update game logic here

        // Draw everything
        BeginDrawing();
        ClearBackground(RAYWHITE);
        DrawText("Welcome to HotOnes!", 190, 200, 20, LIGHTGRAY);
        EndDrawing();
    }

    // Clean up and close the window
    CloseWindow();
    return 0;
}