// HotOnes - C++ main
// Generated by Meow
#include <Hotones.hpp>
#include <iostream>
#include <raylib.h>
#include <stdio.h>
#include <stdlib.h>
#include <string>


#include <SoundBus.hpp>
#include <Player.hpp>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <thread>
#include <vector>

using namespace Hotones;

Camera3D* Hotones::core::camera = nullptr;

 int main() {
    Hotones::core appCore; // initialize static camera
    Player player; // controllable player instance
    // Initialize the window
    InitWindow(800, 600, "HotOnes");
    while (!WindowShouldClose()) {
      // Update game logic here
      player.update();

      // Draw everything
      BeginDrawing();
      BeginMode3D(*Hotones::core::camera);
      player.render();
      if (IsKeyPressed(KEY_SPACE)) {
        std::cout << "Space key pressed!" << std::endl;
      }
      ClearBackground(RAYWHITE);
      DrawText("Welcome to HotOnes!", 190, 200, 20, LIGHTGRAY);
      EndMode3D();
      EndDrawing();
    }
    // Clean up and close the window
    CloseWindow();
    return 0;
  }